// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.21.12
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "auth.v1";

export enum Role {
  MASTER = 0,
  SALON = 1,
  UNRECOGNIZED = -1,
}

export interface RegisterRequest {
  email: string;
  password: string;
  passwordConfirm: string;
  role: Role;
}

export interface RegisterResponse {
  ok: boolean;
  message: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface TokensResponse {
  accessToken: string;
  refreshToken: string;
}

export interface VerifyRequest {
  token: string;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

export interface AuthServiceClient {
  register(request: RegisterRequest): Observable<RegisterResponse>;

  login(request: LoginRequest): Observable<TokensResponse>;

  verify(request: Empty): Observable<TokensResponse>;

  refresh(request: Empty): Observable<TokensResponse>;
}

export interface AuthServiceController {
  register(request: RegisterRequest): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  login(request: LoginRequest): Promise<TokensResponse> | Observable<TokensResponse> | TokensResponse;

  verify(request: Empty): Promise<TokensResponse> | Observable<TokensResponse> | TokensResponse;

  refresh(request: Empty): Promise<TokensResponse> | Observable<TokensResponse> | TokensResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "verify", "refresh"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
